### PR TITLE
Add config key for 'gpgKeys' and allow multiple keyRefs when signing with gpg, fixing Issues #309 and #691

### LINKED ISSUE #309: Enable specifying GPG key id in aptly.conf
It would be helpful if the signing GPG key id could be specified in aptly.conf.

### PR DESCRIPTION
**Pull request by abregar**
Fixes #309 and #691 

## Requirements

All new code should be covered with tests, documentation should be updated. CI should pass.

## Description of the Change

This PR introduces support for multiple GPG signing keys in aptly, addressing longstanding requests for multi-signature support in published repositories.
The change was motivated by Debian repository guidelines and our internal requirement to rotate signing keys without interrupting package consumers.

- Implements repeatable --gpg-key CLI flag.
- Adds gpgKeys array to aptly.conf for configuration-based multi-key support.
- CLI arguments take precedence over configuration file values.
- Both clearsign and detach-sign operations now sign with all provided keys.
- updated some unit tests 

## Checklist

- [x] unit-test updated (if change is algorithm)
- [x] functional test added/updated (if change is functional)
- [ ] man page updated (if applicable)
- [ ] bash completion updated (if applicable)
- [x] documentation updated
- [x] author name in `AUTHORS`

### CODE REVIEW

File: utils/config_test.go [hunk 1]
```diff
@@ -376,4 +379,4 @@ packagepool_storage:
 `
 const configFileYAMLError = `packagepool_storage:
     type: invalid
-`
```
Comment (neolynx) [inline utils/config_test.go:379]: extra newline ?

File: api/publish.go [hunk 2]
```diff
@@ -16,8 +16,8 @@ import (
 type signingParams struct {
 	// Don't sign published repository
 	Skip bool `                json:"Skip"           example:"false"`
-	// GPG key ID to use when signing the release, if not specified default key is used
-	GpgKey string `            json:"GpgKey"         example:"A0546A43624A8331"`
+	// GPG key ID(s) to use when signing the release, CSV if multiple keys, if not specified default configured key(s) are used
+	GpgKey string `            json:"GpgKey"         example:"KEY_ID_a,KEY_ID_b"`
```
Comment (neolynx) [inline api/publish.go:20]: do we allow a space after the comma ? I would add it in the example if yes, looks nicer

**Comment by neolynx** [comment]
looks good otherwise ! :+1:

**Comment by andrewshadura** [comment]
Hello, is there anything blocking this? Can I help somehow?

**Comment by neolynx** [comment]
finally rebased and coverage working again !

we should get the coverage a bit higher, I think adding a api test with multiple keys will do...

**Comment by neolynx** [comment]
I've added a new test which checks that api publish is signing with two keys, Patch coverage is 88.88889% :-)
